-- @generated by web db:generate
PRAGMA foreign_keys = ON;

CREATE TABLE "Todo" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "done" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_Todo_done_createdAt" ON "Todo" ("done", "createdAt");
